Camjaira/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib import auth
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py

from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home),
    path('test/', views.test),
    path('about/', views.about),
    path('login/', views.login),
    path('user/', views.userPage),
    path('logout/', views.logout),
    path('contact/', views.contact),
    path('services/', views.services),
    path('list-room/', views.roomList),
    path('forbidden/', views.forbidden),
    path('register/', views.registerUser),
    path('create-room/', views.roomCreate),
    path('appointments/', views.appointments),
    path('edit-room/<int:id>', views.roomEdit),
    path('show-room/<int:id>', views.roomDetail),
    path('delete-room/<int:id>', views.deleteRoom),
    path('suggestion-list/', views.suggestionList),
    path('suggestion-create/', views.suggestionCreate),
    path('resolve-suggestion/<int:id>',views.resolveSuggestion),
    path('wipe-appointments/', views.wipeAppointments),
    path('favourite-suggestion/<int:id>',views.favouriteSuggestion),
    path('show-reviews-room/<int:id>', views.roomListReview),
    path('add-review/<int:roomID>', views.addReview),
    path('delete-appointment/<int:id>', views.deleteAppointment),
    path('resolve-appointment/<int:id>', views.resolveAppointment),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Room(models.Model):
    # Information provided by the owner
    number = models.CharField(max_length=20)
    description = models.TextField(blank = True)
    floor = models.IntegerField()
    type = models.CharField(max_length=50)
    image = models.ImageField(upload_to='room_images',blank = True, default='room_images/placeholder.png')
    size = models.IntegerField()
    price = models.FloatField()
    availability = models.BooleanField(default = True)

    # Fields handled by the server
    visitCount = models.IntegerField(default = 0)
    lastUpdated = models.DateTimeField(auto_now = True)

class RoomAmenity(models.Model):
    roomID = models.ForeignKey(Room, on_delete=models.CASCADE)
    name = models.CharField(max_length = 50)
    description = models.TextField(blank = True)

class Appointment(models.Model):
    # Information the visitor submits
    name = models.CharField(max_length=200)
    email = models.EmailField()
    scheduledDate = models.DateField()
    topic = models.CharField(max_length=50)
    message = models.TextField(blank = True)
    

    # Fields initialized by the server
    userID = models.ForeignKey(User, on_delete=models.CASCADE)
    ipAddress = models.GenericIPAddressField()
    timeStamp = models.DateTimeField(auto_now = True)
    resolved = models.BooleanField(default = False)

class Review(models.Model):
    cleanlinessRating = models.IntegerField()
    aestheticRating = models.IntegerField()
    comfortRating = models.IntegerField()
    valueRating = models.IntegerField()

    comment = models.TextField(blank = True)

    # Fields initialized by the server
    roomID = models.ForeignKey(Room, on_delete=models.CASCADE)
    userID = models.ForeignKey(User, on_delete=models.CASCADE)
    timeStamp = models.DateTimeField(auto_now = True)

class Suggestion(models.Model):
    topic = models.CharField(max_length=50)
    message = models.TextField(blank = True)

    # Fields initialized by the server
    favourite = models.BooleanField(default = False)
    userID = models.ForeignKey(User, on_delete=models.CASCADE)
    timeStamp = models.DateTimeField(auto_now = True)
    resolved = models.BooleanField(default = False)

# This class acts as an extension to Django's built in user
# For now, it provides a way to store profile pictures.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='user_profile_images', blank = True)

main/views.py
from django.core.files.storage import FileSystemStorage
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.contrib import auth
from .modelInterface import *
from .utility import *

mainPath = 'main/'


def test(request):
    # The test function is used to test any new feature i add
    # It makes it easier since i have one dedicated test page

    context = {
        'recent': getRecentPosts(),
        'suggestion':getSuggestions()
    }

    return render(request, mainPath + 'Account.html/', context=context)

def roomList(request):
    queryData = None

    priceMin = parseFloat(request.GET.get('priceMin', '0'))
    priceMax = parseFloat(request.GET.get('priceMax', '0'))


    if request.method == 'GET':
        queryData = {
            'query': request.GET.get('query', ''),
            'queryType': request.GET.get('queryType', 'type'),
            'priceMin': priceMin,
            'priceMax': priceMax,
            'orderField': request.GET.get('orderField', 'id'),
            'orderDirection': (request.GET.get('orderDirection', 'ascending') == 'ascending'),
        }

        context = {
            'recent': getRecentPosts(),
            'rooms': getRooms(queryData),
        }

    return render(request, mainPath + 'roomTable.html', context=context)


def services(request):

    context = {
        'recent': getRecentPosts(),
        'rooms': getFeaturedRooms(100),
    }

    return render(request, mainPath + 'services.html', context=context)

def forbidden(request):
    return render(request, mainPath + 'forbidden.html', context=None)

def home(request):
    context = {
        'recent': getRecentPosts(),
        'rooms': getFeaturedRooms()
    }

    return render(request, mainPath + 'index.html', context=context)


def login(request):

    context = {
        'recent': getRecentPosts(),
    }

    return render(request, mainPath + 'login.html', context=context)


def contact(request):
    status = False
    if isUser(request):

        if request.method == "POST":
            data = {
                "name": request.POST['name'],
                "email": request.POST['email'],
                "topic": request.POST['topic'],
                "scheduledDate": request.POST['scheduledDate'],
                "message": request.POST['message'],
                "ipAddress": request.META.get("REMOTE_ADDR"),
                "userID":request.user
            }
            addAppointmentRecord(data)
            status = True

        context = {
                'recent': getRecentPosts(),
                'appointmentSaveStatus': status,
            }
            
        return render(request, mainPath + 'contact.html', context=context)
    else:
        return redirect('/login')



def about(request):

    context = {
        'recent': getRecentPosts(),
    }

    return render(request, mainPath + 'about.html', context=context)


def appointments(request):
    if request.method == 'GET' and isOwner(request):
        showResolved = (request.GET.get('showResolved', 'off') == 'on')
        context = {
                'recent': getRecentPosts(),
                'rooms': getFeaturedRooms(),
                'appointments': getAppointments(showResolved),
                'appointmentParams': request.GET,
            }
        return render(request, mainPath + 'appointments.html', context=context)
    else:
        return redirect('/forbidden')


def deleteAppointment(request, id: int):
    deleteAppointmentRecord(id)
    return redirect('/appointments')


def wipeAppointments(request):
    wipeAppointmentRecords()
    return redirect('/appointments')


def resolveAppointment(request, id: int):
    resolveAppointmentRecord(id)
    return redirect('/appointments')


def deleteRoom(request, id: int):
    deleteRoomRecord(id)
    return redirect('/services')


def roomEdit(request, id: int):
    status = False
    if request.method == "POST" and request.user.is_authenticated:
        data = {
            "number": request.POST['number'],
            "description": request.POST['description'],
            "availability": (request.POST.getlist('availability') != []),
            "type": request.POST['type'],
            "floor": request.POST['floor'],
            "price": request.POST['price'],
            "size": request.POST['size'],
            'image': request.FILES.get('image')
        }
        roomID = request.POST['roomID']
        print(data['image'])
        # If no image selected, lets the record keep the old one.
        if request.FILES.get('image') == None:
            data['image'] = getRoomImage(roomID)


        saveRoomRecord(data=data, id=roomID)
        status = True

    context = {
        'recent': getRecentPosts(),
        'room': getRoom(id),
        'roomSaveStatus': status,
    }

    if request.user.is_authenticated:
        return render(request, mainPath + 'roomEdit.html', context=context)
    else:
        return render(request, mainPath + 'forbidden.html', context=None)

def roomCreate(request):
    context = {
        'recent': getRecentPosts(),
    }
    if request.method == "POST" and request.user.is_authenticated and isOwner(request):
        data = {
            "number": request.POST['number'],
            "description": request.POST['description'],
            "availability": (request.POST.getlist('availability') != []),
            "type": request.POST['type'],
            "floor": request.POST['floor'],
            "price": request.POST['price'],
            "size": request.POST['size'],
            'image': request.FILES.get('image')
        }
        saveRoomRecord(data = data)
        return redirect('/services/')

    if request.user.is_authenticated and isOwner(request):
        return render(request, mainPath + 'roomCreate.html', context=context)
    else:
        return render(request, mainPath + 'forbidden.html', context=None)


def login(request):
    context = {
        'recent': getRecentPosts(),
        'loginStatus': ''
    }

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(request, username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:
            context['loginStatus'] = 'Username or Password does not match with an account'

    return render(request, mainPath + 'login.html', context=context)


def logout(request):
    auth.logout(request)
    return redirect('/')


def roomDetail(request, id: int):
    context = {
        'recent': getRecentPosts(),
        'room': getRoom(id),
        'averages':getReviewAverageScores(id),
    }

    return render(request, mainPath + 'roomDetail.html', context=context)

def registerUser(request):
    context = {
        'recent': getRecentPosts(),
    }

    if request.method == 'POST':
        register(request.POST, request.FILES['avatar'])
        return redirect('/')
    else:
        return render(request, mainPath + 'registerUser.html', context=context)

def userPage(request):
    userGroup = None
    if request.user.groups.all():
        userGroup = request.user.groups.all()[0]
    else:
        return redirect('/login')

    context = {
        'recent': getRecentPosts(),
        'accountType': userGroup,
        'superUser': request.user.is_superuser,
        'picture': getUserPicture(request.user.id),
        'userid': request.user.id,
        'username':request.user.username,
        'isUser': isUser(request),
        'isAdmin': isAdmin(request),
        'isOwner': isOwner(request),
    }
    return render(request, mainPath + 'userPage.html/', context=context)

def roomListReview(request, id: int):

    context = {'recent':getRecentPosts(),
                'reviewList':getReviews(id)
                }

    return render(request, mainPath + 'roomListReview.html/', context=context)

def suggestionList(request):
    if request.method == 'GET' and (isOwner(request) or isAdmin(request)):
        showResolved = (request.GET.get('showResolved', 'off') == 'on')
        showFavourite = (request.GET.get('showFavourite', 'off') == 'on')
        context = {
                'recent': getRecentPosts(),
                'suggestions': getSuggestions(showResolved, showFavourite),
            }
        return render(request, mainPath + 'suggestionList.html', context=context)
    else:
        return redirect('/forbidden')

def suggestionCreate(request):
    context = {'recent':getRecentPosts()}

    if request.method == 'POST' and isUser(request):
        data = {
                'topic': request.POST['topic'],
                'message' :request.POST['message'],
                'userID' : request.user}

        addSuggestionRecord(data)

    return render(request, mainPath + 'suggestionCreate.html/', context=context)

def resolveSuggestion(request, id: int):
    toggleResolvedSuggestion(id)
    return redirect('/suggestion-list')

def favouriteSuggestion(request, id: int):
    toggleFavouriteSuggestion(id)
    return redirect('/suggestion-list')

def addReview(request, roomID:int):
    context = {'recent':getRecentPosts()}
    if request.user.is_authenticated and isUser(request):
        if request.method == "POST":
            data = {
                "cleanlinessRating": request.POST.get('cleanlinessRating',0),
                "aestheticRating": request.POST.get('aestheticRating',0),
                "comfortRating": request.POST.get('comfortRating',0),
                "valueRating": request.POST.get('valueRating',0),

templates/main/about.html
{% extends "main/base.html" %}
{% load static %}
{% block title %}About Us{% endblock %}

{% block content %}
<!-- about-->
<div class="about">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="titlepage">
                    <h2>About us</h2>
                    <p>Based in Taguig with clients & team members all over Manila </p>
                </div>
            </div>
            <div class=" col-sm-12">
                <div class="about_box">
                    <div class="row d_flex">
                        <div class="col-md-5">
                            <div class="about_box_text">
                                <h3>Camjaira Rental Services</h3>
                                <p>As one of the best Rental Services system, A website is made to further promote and
                                    expand the influence our rentals services can provide.
                                </p>
                                
                            </div>
                        </div>
                        <div class=" col-md-7  pppp">
                            <div class="about_box_img">
                                <figure><img src="{% static 'images/about_img.png' %}" alt="#" /></figure>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end about-->
{% endblock %}

templates/main/appointments.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Appointments{% endblock %}

{% block content %}
{% include 'main/components/appointmentTable.html' %}

{% endblock %}

templates/main/forbidden.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Forbidden{% endblock %}

{% block content %}
<div class="container my-5">
    <div class="row">
        <div class="col-12">
            <h1 class="text-center">Forbidden access</h1>
        </div>
    </div>
</div>

{% endblock %}

templates/main/index.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Camjaira{% endblock %}

{% block content %}

<!-- start slider section -->
<div class="banner_main" style="background-attachment: fixed;background-size: cover;background-position: 50% 0% ;">
   <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
         <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
         <li data-target="#myCarousel" data-slide-to="1"></li>
      </ol>
      <div class="carousel-inner">
         <div class="carousel-item active">
            <div class="container">
               <div class="carousel-caption relative">
                  <div class="bg_white">
                     <h1>The all new C<span class="yello">a</span>mJaira Rental Services System</h1>
                     <p>Start by browsing a room and setting an appointment directly with the owner after selecting the
                        rooms you are interested in renting in. Without the hassle of physical interaction, with just
                        one click, our company will immediately answer to you</p>
                  </div>
                  <a class="read_more ban_btn" href="/services/">Read More</a>
               </div>
            </div>
         </div>
         <div class="carousel-item">
            <div class="container">
               <div class="carousel-caption relative">
                  <div class="bg_white">
                     <h1>Where are you going this week, C<span class="yello">a</span>mJaira can get you covered.</h1>
                     <p>We created a flexible search system to help filter your queries.</p>
                  </div>
                  <a class="read_more ban_btn" href="/list-room/">Read More</a>
               </div>
            </div>
         </div>
      </div>
      <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
         <span class="carousel-control-prev-icon" aria-hidden="true"></span>
         <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
         <span class="carousel-control-next-icon" aria-hidden="true"></span>
         <span class="sr-only">Next</span>
      </a>
   </div>
</div>
<!-- end slider section -->

<!-- six_box-->
<div id="about">
   <style>
      .wave-divider {
         transform: translateY(-12vh);
      }

      .wave-divider svg {
         position: relative;
         display: block;
         width: 100%;
         height: 40vh;
         margin-block: -1px;
         padding: 0;
      }
   </style>
   <div class="wave-divider">
      <svg id="visual" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1">
         <path
            d="M0 89L55.5 84.5C111 80 222 71 333.2 68.2C444.3 65.3 555.7 68.7 666.8 64C778 59.3 889 46.7 1000 44.8C1111 43 1222 52 1333.2 50.7C1444.3 49.3 1555.7 37.7 1666.8 31.2C1778 24.7 1889 23.3 1944.5 22.7L2000 22L2000 101L1944.5 101C1889 101 1778 101 1666.8 101C1555.7 101 1444.3 101 1333.2 101C1222 101 1111 101 1000 101C889 101 778 101 666.8 101C555.7 101 444.3 101 333.2 101C222 101 111 101 55.5 101L0 101Z"
            fill="#ec2020" stroke-linecap="round" stroke-linejoin="miter"></path>
         <path transform="translate(0,101)"
            d="M0 251L66.7 239.2C133.3 227.3 266.7 203.7 400 182.8C533.3 162 666.7 144 800 167C933.3 190 1066.7 254 1200 242C1333.3 230 1466.7 142 1600 150.8C1733.3 159.7 1866.7 265.3 1933.3 318.2L2000 371L2000 0L1933.3 0C1866.7 0 1733.3 0 1600 0C1466.7 0 1333.3 0 1200 0C1066.7 0 933.3 0 800 0C666.7 0 533.3 0 400 0C266.7 0 133.3 0 66.7 0L0 0Z"
            fill="#ffd413"></path>
         <path transform="translate(0,100)"
            d="M0 189L66.7 173C133.3 157 266.7 125 400 125.3C533.3 125.7 666.7 158.3 800 175.2C933.3 192 1066.7 193 1200 170.3C1333.3 147.7 1466.7 101.3 1600 75.3C1733.3 49.3 1866.7 43.7 1933.3 40.8L2000 38L2000 0L1933.3 0C1866.7 0 1733.3 0 1600 0C1466.7 0 1333.3 0 1200 0C1066.7 0 933.3 0 800 0C666.7 0 533.3 0 400 0C266.7 0 133.3 0 66.7 0L0 0Z"
            fill="#ec2020"></path>
      </svg>
   </div>
   <div class="container">
      <div class="row">
         <div class="col-sm-12">
            <div class="titlepage">
               <h2>About us</h2>
               <p>Based in Taguig with clients & team members all over Manila </p>
            </div>
         </div>
         <div class=" col-sm-12">
            <div class="about_box">
               <div class="row d_flex">
                  <div class="col-md-5">
                     <div class="about_box_text">
                        <h3>CamJaira Rental Services</h3>
                        <p>As one of the best Rental Services system. The website is made to further promote and expand
                           the influence our rentals services can provide.
                        </p>
                        <div class="d-flex justify-content-md-start justify-content-center">
                           <a class="read_more" href="Javascript:void(0)">Read More</a>
                        </div>
                     </div>
                  </div>
                  <div class=" col-md-7  pppp">
                     <div class="about_box_img">
                        <figure><img src="{% static 'images/about_img.png' %}" alt="#" /></figure>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- end six_box-->
<!-- building -->
<div class="building">
   <div class="container">
      <div class="row">
         <div class="col-md-12">
            <div class="titlepage">
               <h2> A BUILDING IS NOT SOMETHING TO<br><span class="yellow">FINISH<br></span> IT IS SOMETHING TO<br><span
                     class="yello">START<br></span></h2>
               <p>CamJaira has always known the importance of buildings, at the surface level they are shelter.
                  But CamJaira builds rooms not only as a shelter, but as an experience for our customers.
                  We aren't only building concrete, we also are building relationships.
               </p>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- end building -->
<!-- % include 'main/components/roomListFeatured.html' % -->

<div class="services_main">
   <div class="container my-5">
      <div class="row">
         <div class="col-12">
            {% include 'main/components/roomList.html' %}
         </div>
      </div>
      <div class="row">
         <div class="col-12 d-flex justify-content-md-start justify-content-center">
            <a class="read_more mt-5" href="/services/">Browse More</a>
         </div>
      </div>
   </div>
</div>


<!-- instant -->
<div class="instant">
   <div class="container-fluid w-75 mx-auto">
      <div class="row">
         <div class="col-md-6 col-12 d-flex justify-content-md-end justify-content-center">
            <div class="titlepage text_align_left">
               <h2>Set an Appointment Today</h2>
               <p>Start by setting an appointment directly with the owner after selecting the rooms you are
                  interested
                  in renting in. Without the hassle of physical interaction, with just one click, our company will
                  immediately answer to you</p>
               <div class="w-100 d-flex justify-content-md-start justify-content-center"><a class="read_more"
                     href="/contact/">Set an Appointment</a>
               </div>
            </div>
         </div>
         <div class="col-md-6 col-12 d-flex align-items-center">
            <div class="instant_img">
               <figure><img src="{% static 'images/pc.png' %}" alt="#" /></figure>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- end instant -->
{% endblock %}

templates/main/login.html
{% extends "main/base.html" %}
{% load static %}

{% block title %} Login {% endblock %}

{% block content %}

<div class="container-fluid contact">
    <div class="container my-5">
        <div class="row d-flex justify-content-center">
            <div class="col-12">
                <div class="titlepage p-0 text-md-left text-center">
                    <h2>Login Page</h2>
                </div>
            </div>

        </div>
        <div class="row my-5">
            <div class="col-12 d-flex justify-content-center">
                <form name="login" class="main_form" method="post">
                    {% csrf_token %}
                    <input class="form-control" placeholder="Username" type="text" name="username">
                    <input class="form-control" placeholder="*****" type="password" name="password">
                    <button class="send">Send</button>
                </form>
            </div>
        </div>
        <div class="row my-5">
            <div class="col-12 d-flex text-center justify-content-center">
                <p class="text-center justify-content-center ">{{loginStatus}}</p>
            </div>
        </div>
        <a href="/register" style="text-align:center;outline:red solid 2px; font-size: large;">Don't have an account? Create one</a>
    </div>

</div>
{% endblock %}

templates/main/reviewCreate.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Sexy{% endblock %}

{% block content %}

<div class="container-fluid contact">
    <div class="container my-5">
        <div class="row d-flex justify-content-center">
            <div class="col-12">
                <div class="titlepage p-0 text-md-left text-center">
                    <h2>Create a Review!</h2>
                </div>
            </div>

        </div>
        <div class="row my-5">
            <div class="col-12 d-flex justify-content-center">
                <form method="POST" class="row">
                    {% csrf_token %}
                    <div class="col-12">
                        <label>cleanliness</label>
                        <input type="number" name="cleanlinessRating"></input>
                        <label>aesthetic</label>
                        <input type="number" name="aestheticRating"></input>
                        <label>comfortRating</label>
                        <input type="number" name="comfortRating"></input>
                        <label>valueRating</label>
                        <input type="number" name="valueRating"></input>
    
                    </div>

                    <div class="col-12">
                        <label>Comment</label>
                        <textarea name="comment"></textarea>
    
                    </div>
                
                    <input type="submit">
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/main/roomListReview.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Sexy{% endblock %}

{% block content %}

<table style="width:90%; margin-inline:auto">
    <tr>
        <th>Review Scores</th>
        <th>Comment</th>
        <th>Posting User</th>
    </tr>

    {% for i in reviewList %}
    <tr>
        <td>
            <ul>
                <li>cleanlinessRating: {{i.cleanlinessRating}}</li>
                <li>aestheticRating: {{i.aestheticRating}}</li>
                <li>comfortRating: {{i.comfortRating}}</li>
                <li>valueRating: {{i.valueRating}}</li>
            </ul>
        </td>
        <td>
            {{i.comment}}
        </td>
        <td>
            {{i.userID}}
        </td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

templates/main/suggestionCreate.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Post suggestion ok{% endblock %}

{% block content %}


<div class="container-fluid contact">
    <div class="container my-5">
        <div class="row d-flex justify-content-center">
            <div class="col-12">
                <div class="titlepage p-0 text-md-left text-center">
                    <h2>Submit a suggestion!</h2>
                </div>
            </div>

        </div>
        <div class="row my-5">
            <div class="col-12 d-flex justify-content-center">
                <form method="POST" enctype="multipart/form-data" class="row">
                    {% csrf_token %}
                    <div class="col-12">
                        <label for="id_topic">Topic:</label>    
                        <input type="text" name="topic" id="id_topic" maxlength="50" required>
                    </div>
                    
                    <div class="col-12">
                        <label for="id_message">Message:</label>
                    <textarea name="message" id="id_message" rows="4" cols="40"></textarea>
                    </div>
                    
                  
                    <input type="submit" value="Submit">
                </form>
            </div>
        </div>
        <div class="row my-5">
            <div class="col-12 d-flex text-center justify-content-center">
                <p class="text-center justify-content-center ">{{loginStatus}}</p>
            </div>
        </div>
        <a href="/register" style="text-align:center;outline:red solid 2px; font-size: large;">Don't have an account? Create one</a>
    </div>

</div>
{% endblock %}

templates/main/suggestionList.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Sexy{% endblock %}

{% block content %}
<h1>Suggestions</h1>

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <form method="get">
                <label for="id_favourite">Show Favourite:</label>
                <input type="checkbox" name="showFavourite" id="id_favourite">

                <label for="id_resolved">Show resolved:</label>
                <input type="checkbox" name="showResolved" id="id_resolved">

                <input type="submit">
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <table style="width:100%">
                {% for i in suggestions %}
                    <tr>
                        <td>ID: {{i.id}}</td>
                        <td>Topic: {{i.Topic}}</td>
                        <td>
                            {{i.message}}
                        </td>
                        <td>
                            <ul>
                                <li><a href="/favourite-suggestion/{{i.id}}">favourite: {{i.favourite}}</a></li>
                                <li>userID: {{i.userID}}</li>
                                <li>timeStamp: {{i.timeStamp}}</li>
                                <li><a href="/resolve-suggestion/{{i.id}}">resolved: {{i.resolved}}</a></li>
                            </ul>
                        </td>

                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>

{% endblock %}